framework:
    trusted_proxies: 'private_ranges'
    trusted_headers: ['x-forwarded-for', 'x-forwarded-proto', 'x-forwarded-port', 'x-forwarded-host']
    router:
        default_uri: '%env(default::APP_URL)%'
    session:
        save_path: '%kernel.project_dir%/var/sessions'
        cookie_secure: auto
        cookie_samesite: lax
